# Generated by Django 4.2.1 on 2024-05-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_checkout_contact_wishlist_checkoutproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='rppid',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
